config/routes.rb
# Q's Web Accounting Book
# Copyright (c) 2002-2007,2010-2011,2013,2024 Hisashi HORIKAWA. All rights reserved.
#   https://www.nslabs.jp/ac/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# ルーティング
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest


  # You can have the root of your site routed with "root"
  root :to => 'welcome#index'

  # 単数形は `controller:` でクラスを指定.
  resource :account, controller:'account' do
    # Sorcery と名前が被る。`login`, `logout` は避ける
    get 'sign_in'
    post 'sign_out'
  end

  # RP として振る舞う
  namespace :connect do
    # とりあえず Google を使う. TODO: `accounts.nslabs.jp` に切り替えること
    resource :google_oauth2, only:[:create, :show], controller:'google_oauth2'
  end


  # グローバルマスタ########################################################
  
  # 消費税マスタ
  resources :vats

  # 為替レート
  # ●●
  
  
  resources :books do
    # 管理 ########################################################
    
    member do
      # 締め処理
      get :period_end_close
    end

    # 会計期間
    resources :period_ends

    
    # 財務会計 ########################################################
    
    # 会計部門マスタ
    resources :divisions do
      member do
        post :enable_div
      end
    end
    
    # 勘定科目マスタ
    resources :account_titles do
      member do
        post :enable_ac
      end
    end

    # 仕訳帳・振替伝票
    resources :journals do
      # `:id` 伝票番号 + date= 伝票日付
      member do 
        post 'add_line'
      end
      collection do # `:id` なし
        get 'list'
        #post 'remove_line' クライアント側で実装
      end
    end
    
    # 予定取引
    # ●●

    # 総勘定元帳.
    # `:id` は不要. コントローラは `GeneralLedgersController`
    resource :general_ledger do
      collection do
        get 'list'
      end
    end

    # 簡易な固定資産
    # ●●

    # 予算 -- バージョン管理があるから複数形
    resources :budgets do
    end

    # 科目別税区分別消費税集計表
    # ●●

    # 財務諸表テンプレート
    resources :report_templates do
    end

    # 財務諸表テンプレートの各科目
    resources :reporting_titles do
      collection do
        #post 'new_line'
      end

      member do
        post 'edit_cxl'
      end
    end

    # 財務諸表・予算実績対比
    resource :statements do
      collection do
        get 'list'
        # 月次推移
        get 'month'
      end
    end

    
    # 販売管理 ########################################################

    # 販売請求書
    # ●●

    
    # 購買管理 ########################################################

    # (購買) 請求書
    resources :invoices

    # 経費精算
    resources :expenses

    
    # 取引先 ########################################################

    # 取引先マスタ
    resources :partners do
      collection do
        get "search"
      end
    end

    
    # 入出金 ########################################################

    # 取引照合: Credit Card Reconciliation
    resources :cc_reconciliations

    # 銀行振込み
    resources :payments

    # 出納帳
    # `:id` は不要
    resource :cashbook

    # 資金口座マスタ
    resources :cash_accounts
  
    # 金融投資
    # ●●

    # 借入金
    # ●●

  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cc_reconciliation.rb
# -*- coding: utf-8 -*-

# Q's Web Accounting Book
# Copyright (c) 2002-2007,2010-2011,2013 HORIKAWA Hisashi. All rights reserved.
#   http://www.nslabs.jp/ac/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# クレジットカードの引き落とし (預金と照合)
class CcReconciliation < ApplicationRecord
  # 親
  belongs_to :book

  # 支払い口座
  belongs_to :cash_account
  
  # 支払いの明細行
  has_many :cc_reconc_details

  validates_presence_of :date
  
end

app/controllers/cc_reconciliations_controller.rb
# Q's Web Accounting Book
# Copyright (c) 2002-2007,2010-2011,2013,2024 Hisashi HORIKAWA. All rights reserved.
#   https://www.nslabs.jp/ac/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# 取引照合: クレジットカード照合
class CcReconciliationsController < ApplicationController
end

app/views/cc_reconciliations/_cc_reconciliation.html.erb
<div id="<%= dom_id cc_reconciliation %>">
</div>

app/views/cc_reconciliations/_form.html.erb
<%= form_with(model: cc_reconciliation) do |form| %>
  <% if cc_reconciliation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cc_reconciliation.errors.count, "error") %> prohibited this cc_reconciliation from being saved:</h2>

      <ul>
        <% cc_reconciliation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cc_reconciliations/edit.html.erb
<% content_for :title, "Editing cc reconciliation" %>

<h1>Editing cc reconciliation</h1>

<%= render "form", cc_reconciliation: @cc_reconciliation %>

<br>

<div>
  <%= link_to "Show this cc reconciliation", @cc_reconciliation %> |
  <%= link_to "Back to cc reconciliations", cc_reconciliations_path %>
</div>

app/views/cc_reconciliations/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Cc reconciliations" %>

<h1>Cc reconciliations</h1>

<div id="cc_reconciliations">
  <% @cc_reconciliations.each do |cc_reconciliation| %>
    <%= render cc_reconciliation %>
    <p>
      <%= link_to "Show this cc reconciliation", cc_reconciliation %>
    </p>
  <% end %>
</div>

<%= link_to "New cc reconciliation", new_cc_reconciliation_path %>

app/views/cc_reconciliations/new.html.erb
<% content_for :title, "New cc reconciliation" %>

<h1>New cc reconciliation</h1>

<%= render "form", cc_reconciliation: @cc_reconciliation %>

<br>

<div>
  <%= link_to "Back to cc reconciliations", cc_reconciliations_path %>
</div>

app/views/cc_reconciliations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cc_reconciliation %>

<div>
  <%= link_to "Edit this cc reconciliation", edit_cc_reconciliation_path(@cc_reconciliation) %> |
  <%= link_to "Back to cc reconciliations", cc_reconciliations_path %>

  <%= button_to "Destroy this cc reconciliation", @cc_reconciliation, method: :delete %>
</div>