config/routes.rb
# Q's Web Accounting Book
# Copyright (c) 2002-2007,2010-2011,2013,2024 Hisashi HORIKAWA. All rights reserved.
#   https://www.nslabs.jp/ac/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# ルーティング
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest


  # You can have the root of your site routed with "root"
  root :to => 'welcome#index'

  # 単数形は `controller:` でクラスを指定.
  resource :account, controller:'account' do
    # Sorcery と名前が被る。`login`, `logout` は避ける
    get 'sign_in'
    post 'sign_out'
  end

  # RP として振る舞う
  namespace :connect do
    # とりあえず Google を使う. TODO: `accounts.nslabs.jp` に切り替えること
    resource :google_oauth2, only:[:create, :show], controller:'google_oauth2'
  end


  # グローバルマスタ########################################################
  
  # 消費税マスタ
  resources :vats

  # 為替レート
  # ●●
  
  
  resources :books do
    # 管理 ########################################################
    
    member do
      # 締め処理
      get :period_end_close
    end

    # 会計期間
    resources :period_ends

    
    # 財務会計 ########################################################
    
    # 会計部門マスタ
    resources :divisions do
      member do
        post :enable_div
      end
    end
    
    # 勘定科目マスタ
    resources :account_titles do
      member do
        post :enable_ac
      end
    end

    # 仕訳帳・振替伝票
    resources :journals do
      # `:id` 伝票番号 + date= 伝票日付
      member do 
        post 'add_line'
      end
      collection do # `:id` なし
        get 'list'
        #post 'remove_line' クライアント側で実装
      end
    end
    
    # 予定取引
    # ●●

    # 総勘定元帳.
    # `:id` は不要. コントローラは `GeneralLedgersController`
    resource :general_ledger do
      collection do
        get 'list'
      end
    end

    # 簡易な固定資産
    # ●●

    # 予算 -- バージョン管理があるから複数形
    resources :budgets do
    end

    # 科目別税区分別消費税集計表
    # ●●

    # 財務諸表テンプレート
    resources :report_templates do
    end

    # 財務諸表テンプレートの各科目
    resources :reporting_titles do
      collection do
        #post 'new_line'
      end

      member do
        post 'edit_cxl'
      end
    end

    # 財務諸表・予算実績対比
    resource :statements do
      collection do
        get 'list'
        # 月次推移
        get 'month'
      end
    end

    
    # 販売管理 ########################################################

    # 販売請求書
    # ●●

    
    # 購買管理 ########################################################

    # (購買) 請求書
    resources :invoices

    # 経費精算
    resources :expenses

    
    # 取引先 ########################################################

    # 取引先マスタ
    resources :partners do
      collection do
        get "search"
      end
    end

    
    # 入出金 ########################################################

    # 取引照合: Credit Card Reconciliation
    resources :cc_reconciliations

    # 銀行振込み
    resources :payments

    # 出納帳
    # `:id` は不要
    resource :cashbook

    # 資金口座マスタ
    resources :cash_accounts
  
    # 金融投資
    # ●●

    # 借入金
    # ●●

  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/division.rb
# Q's Web Accounting Book
# Copyright (c) 2002-2007,2010-2011,2013,2024 Hisashi HORIKAWA. All rights reserved.
#   https://www.nslabs.jp/ac/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# 会計部門
class Division < ApplicationRecord
  include ActsAsDag
  acts_as_tree

  # システム科目は book_id IS NULL. 
  belongs_to :book, optional: true
  
  has_many :div_ovrds
  def div_ovrd(book)
    raise ArgumentError if self.book_id && self.book_id != book.id
    DivOvrd.where('book_id = ? AND division_id = ?', book.id, self.id).take
  end
  
  validates_presence_of :name

  # 1文字は不可
  validates_presence_of :division_code
  validates :division_code, format: {with: /\A[a-zA-Z][a-zA-Z0-9]+\z/}
  validates :division_code, uniqueness: {scope:["division_code", "book_id"]}
            
  # @note `before_save()` では遅い。
  before_validation :check_fields


  ##########################################################################
  # Class Methods
  
  # 集計部門の一覧. システム部門を含む
  # `options_from_collection_for_select()` の第1引数に渡す
  def self.aggregations(book)
    return Division.where('(book_id IS NULL OR book_id = ?) AND aggregate IS TRUE', book.id)
                   .order(:division_code)
  end

  
  # 木の部分の root の一覧. 運用上, 一つだけ
  def self.tree_roots(book)
    Division.joins('LEFT JOIN (SELECT * FROM division_edges WHERE main_parent IS TRUE) ST ON divisions.id = ST.child_id')
            #.left_outer_joins(:div_ovrds)
            .where('parent_id IS NULL AND (divisions.book_id IS NULL OR divisions.book_id = ?)', book.id)
            .order('division_code')
  end


  # 会計部門のほうは、root が必ず一つ。いったん、グルーピングなしにする。
  # @return 実在科目のみの一覧
  def self.active_items(book, date)
    Division.joins(:div_ovrds)
            .where('(divisions.book_id IS NULL OR divisions.book_id = ?) AND (aggregate IS FALSE) AND (div_ovrds.book_id = ? AND (end_day IS NULL OR end_day > ?))', book.id, book.id, date)
  end

  
  ##########################################################################
  # Instance Methods
  
  def children_json(book)
    ret = []
    self.children.each do |node|
      next if node.book_id && node.book_id != book.id
      r = {  id: node.id, name: node.name,
             aggregate: node.aggregate,
             division_code: node.division_code,
             purchase_active: node.purchase_active,
             vat_disable: node.vat_disable,
             show: "/books/#{book.id}/divisions/#{node.id}",
             active: node.aggregate ? true :
                       (node.div_ovrd(book) ? node.div_ovrd(book).end_day == nil : false)
          }
      r["_children"] = node.children_json(book) if node.aggregate
      ret << r
    end
    return ret
  end

  
  # Root まで、順に辿って hierarchies 表に登録
  # `transaction()` は, 必要があれば, 呼出し側でおこなうこと
  def add_child child, additional_fields = {}
    raise ArgumentError if !self.aggregate

    h = self.class._aat.hierarchy_class
    # 直接の親と、親の先祖全部に張る。後者は、単に直接の親の `ancestors` を使えばいい。
    h.create!( {main_parent: true}.merge(additional_fields)
                                  .merge(parent_id: self.id,
                                         child_id: child.id,
                                         #distance: 1
                                        ))
=begin
    self.ancestor_hierarchies.each do |ancestor_h|
      # ● TODO: ブロックを呼び出すようにしないと、追加フィールドが決められない
      h.create!(ancestor_id: ancestor_h.ancestor_id,
                descendant_id: child.id,
                distance: ancestor_h.distance + 1,
                main_parent: ancestor_h.main_parent )
    end
=end
  end


private
  # for `before_validation()`. `before_save()` では遅い。
  def check_fields
    self.name          = (self.name || "").unicode_normalize(:nfkc)
    self.division_code = (self.division_code || "").unicode_normalize(:nfkc).upcase
  end
  
end

app/controllers/divisions_controller.rb
# Q's Web Accounting Book
# Copyright (c) 2002-2007,2010-2011,2013,2024 Hisashi HORIKAWA. All rights reserved.
#   https://www.nslabs.jp/ac/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# 会計部門マスタ
class DivisionsController < ApplicationController
  # `@book` の設定を兼ねる
  before_action :check_if_user_can_access_book

  before_action :set_division, only: %i[ show edit update destroy enable_div]

  
  # GET /divisions or /divisions.json
  def index
    # System 部門は未利用でも表示.
    #@pagy, @divisions = pagy(
    #            Division.where('book_id IS NULL or book_id = ?', @book.id)
    #                    .order('division_code') )

    @div_ary = []
    Division.tree_roots(@book).each do |root_div|
      r = { id: root_div.id, name: root_div.name,
            aggregate:root_div.aggregate,
            division_code: root_div.division_code,
            active: true,
            "_children": [] }
      r["_children"] = root_div.children_json(@book)
      @div_ary << r
    end
  end

  # POST
  def enable_div
    ovrd = DivOvrd.find_or_initialize_by(
                book_id: @book.id, division_id: @division.id) do |m|
      m.end_day = nil
    end
    ovrd.save!

    index()  # @div_ary を更新
    # turbo frame だと上手くいかない. turbo stream で返す
    render(turbo_stream: turbo_stream.replace("div-frame", partial:"div_frame"))
  end
 
  
  # GET /divisions/1 or /divisions/1.json
  def show
  end

  # GET /divisions/new
  def new
    @admin_user = current_user  # ●● TODO: fix!
    @system_item = @admin_user ? true : false
    
    @division = Division.new
  end

  
  # POST /divisions or /divisions.json
  def create
    @admin_user = current_user  # ●● TODO: fix!
    @system_item = @admin_user ? params[:system_item] : false
    
    @division = Division.new(division_params.permit(
                               %i[aggregate division_code name description purchase_active vat_disable]))
    @end_day  = params[:end_day] 

    if !params[:parent_id].blank?
      parent = Division.where('(book_id IS NULL or book_id = ?) AND aggregate IS TRUE AND divisions.id = ?', @book.id, params[:parent_id])
                       .take
    end

    @division.book_id = @book.id  if !@system_item
      
    # 実在部門を root に置くのは不可
    if !@division.aggregate && !parent
      @division.errors.add :base, "実在部門は root に置けません。"
      render :new, status: :unprocessable_entity
      return
    end

    begin
      ActiveRecord::Base.transaction do
        @division.save!
        if parent
          parent.add_child(@division, main_parent:true)
        end

        if !@system_item
          DivOvrd.create! division_id: @division.id, book_id: @book.id,
                          end_day: @end_day
        end
      end
    rescue ActiveRecord::RecordInvalid
      @parent_id = parent.id if parent
      render :new, status: :unprocessable_entity
      return
    end
    
    redirect_to( {action:'show', id:@division.id},
                 notice: "Division was successfully created." )
  end


  # GET /divisions/1/edit
  def edit
    @admin_user = current_user  # ●● TODO: fix!
    @system_item = @admin_user && !@division.book_id ? true : false
    
    ovrd = @division.div_ovrd(@book)
    @end_day = ovrd ? ovrd.end_day : nil

    @parent_id = @division.main_parent ? @division.main_parent.id : nil
  end

  
  # PATCH/PUT /divisions/1 or /divisions/1.json
  def update
    @admin_user = current_user  # ●● TODO: fix!
    @system_item = @admin_user ? params[:system_item] : false

    @end_day = params[:end_day]

    # ここでは保存しない。
    vat_disable = @division.vat_disable
    @division.assign_attributes(division_params.permit(
                                    %i[division_code name description purchase_active vat_disable]))
    @division.vat_disable = true if vat_disable  # disable から変更不可. TODO: ovrd にもフィールドつくるか?

    if @system_item
      ovrd = @division.div_ovrd(@book)
    else
      # いつでも ovrd をつくる
      ovrd = @division.div_ovrd(@book) || DivOvrd.new(division_id: @division.id, book_id: @book.id)
      ovrd.end_day = @end_day
    end

    ActiveRecord::Base.transaction do
      if @system_item || @division.book_id
        @division.save!
      end
      if !@system_item
        ovrd.save!
      else
        ovrd.destroy! if ovrd
      end
    rescue ActiveRecord::RecordInvalid
      @parent_id = @division.main_parent ? @division.main_parent.id : nil
      render :edit, status: :unprocessable_entity 
      return
    end
    
    redirect_to({action:'show', id:@division},
                  notice: "Division was successfully updated." )
  end

  
  # DELETE /divisions/1 or /divisions/1.json
  def destroy
    @division.destroy!

    redirect_to( {action:'index'},
                 notice: "Division was successfully destroyed." )
  end

  
private
  # Use callbacks to share common setup or constraints between actions.
  def set_division
    @division = Division.where('(book_id IS NULL or book_id = ?) AND id = ?',
                               @book.id, params[:id]).take
    raise ActiveRecord::RecordNotFound if !@division
  end

  # Only allow a list of trusted parameters through.
  def division_params
    params.require(:division)
  end
end

app/views/divisions/_div_frame.html.erb
<div id="div-frame" data-controller="divisions">
  
  <script type="application/json" id="tbl-json-data">
    <%= @div_ary.to_json.html_safe %>
  </script>

  <div id="div-tbl" >
  </div>
</div>

app/views/divisions/_form.html.erb
  <%= error_messages_for form.object %>


<% if @admin_user  %>
  <div class="row mb-3 text-bg-info">
    <label class="col-sm-2 col-form-label">System item:</label>
    <div class="col-sm-10">
      <label class="form-check-label">
        <%= check_box_tag :system_item, '1', @system_item, 
                               class:"form-check-input" %>
        System item の作成・編集
      </label> 
    </div>
  </div>
<% end %>

  <div class="row mb-3">
    <label class="col-sm-2 col-form-label" for="parent_id">親:</label>
    <div class="col-sm-10">
<% if ['new', 'create'].include?(controller.action_name) %>  
      <%= select_tag 'parent_id',
                options_from_collection_for_select(Division.aggregations(@book),
                                                   :id, :name, @parent_id),
              include_blank:"(Root)", class:"form-select" %>
<% else %>
      <%= @division.main_parent ? @division.main_parent.name : "(root)" %>
<% end %>
    </div>
  </div>


  <div class="row mb-3">
    <label  class="col-sm-2 col-form-label">集計部門?:</label>
    <div class="col-sm-10">
<% if controller.action_name != "new" && controller.action_name != 'create' %>
      <%= @division.aggregate ? "集計部門" : "実在部門" %>
<% else %>
      <label class="form-check-label">
        <%= form.radio_button :aggregate, true, class:"form-check-input" %>
        集計部門 (仕訳を発生させない)</label>
      <label class="form-check-label">
        <%= form.radio_button :aggregate, false, class:"form-check-input" %>
        実在部門</label>
      <div class="form-text">
        <em style="color:red">※後から変更できません。</em>
      </div>
<% end %>      
    </div>
  </div>
  
  <div class="row mb-3">
    <label class="col-sm-2 col-form-label" for="end_day">使用終了:</label>
    <div class="col-sm-10">
      <%= date_field_tag :end_day, @end_day, class:"form-control" %> ブランクで active.
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :sort, "表示順:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :division_code, class:"form-control" %> 英字始まり, 英数のみ
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :name, "名前:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :name, class:"form-control" %> 
    </div>
  </div>


  <div class="row mb-3">
    <%= form.label :description, "説明:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_area :description, rows:5, class:"form-control" %> 
    </div>
  </div>


  
<h2>実在部門のみ</h2>

  <div class="row mb-3">
    <label class="col-sm-2 col-form-label">購買請求書・経費精算で利用:</label>
    <div class="col-sm-10">
      <label class="form-check-label">
        <%= form.check_box :purchase_active, class:"form-check-input" %>
        購買請求書で利用
      </label>  ●● TODO: `div_ovrds` のほうも付けること。
    </div>
  </div>

  <div class="row mb-3">
    <label class="col-sm-2 col-form-label">消費税:</label>
    <div class="col-sm-10">
<% if ['new', 'create'].include?(controller.action_name) ||
      !@division.vat_disable %>
      <label class="form-check-label">
        <%= form.check_box :vat_disable, class:"form-check-input" %>
        消費税の計上不可
      </label>
      <div class="form-text">
        <em style="color:red">※後から、計上不可→計上可に変更できません。</em>
      </div>
<% else %>
      ✓ 消費税の計上不可
<% end %>
    </div>
  </div>

app/views/divisions/edit.html.erb
<% @page_title = "会計部門の編集" %>

<%= form_with(model:@division,
              url:{controller:'divisions', action:'update', id:@division.id}) do |form| %>
  <%= render "form", form:form %>


  <div>
    <%= link_to "Cancel", {action:'show', id: @division.id}, class:'btn btn-secondary' %>
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>
  

app/views/divisions/index.html.erb
<% @crumbs = []
   @page_title = "会計部門の一覧" %>


<p>Active列をクリックで「利用する」に変更できます。

<% # separate parts to enable the table refresh.
  %>
<%= render partial: "div_frame" %>
  
<hr />
<p><%= link_to "新しい会計部門...", action:'new' %>

app/views/divisions/new.html.erb
<% @page_title = "新しい会計部門" %>

<%= form_with(model:@division,
              url:{controller:'divisions', action:'create'}) do |form| %>
  <%= render "form", form:form %>

  <div>
    <%= link_to "Cancel", "./", class:'btn btn-secondary' %>
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>
  

app/views/divisions/show.html.erb
<% @crumbs = [
     {name: "会計部門の一覧", link: "./"} # 末尾の "/" 必須
   ]
   @page_title = "会計部門: " + @division.name %>

<table class="table">
  <tr><th>division code: <td><%= @division.division_code %>
  <tr><th>System 部門?:  <td><%= @division.book_id ? "No" : "Yes" %>

  <tr><th>親:
    <td>
<% if @division.parents.size > 0
     @division.parents.each do |parent| %>           
      <%= parent.division_code %>
      <%= parent.name %>
<%   end %>
<% else %>
      親はありません
<% end %>
</table>




<div>
  <%= link_to "Edit this division...", edit_book_division_path(@book, @division) %> |
  <%= button_to "Destroy this division",
                {controller:'divisions', action:'destroy', id: @division.id},
                method: :delete, data:{turbo_confirm:'OK?'} %>
</div>