config/routes.rb
# Q's Web Accounting Book
# Copyright (c) 2002-2007,2010-2011,2013,2024 Hisashi HORIKAWA. All rights reserved.
#   https://www.nslabs.jp/ac/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# ルーティング
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest


  # You can have the root of your site routed with "root"
  root :to => 'welcome#index'

  # 単数形は `controller:` でクラスを指定.
  resource :account, controller:'account' do
    # Sorcery と名前が被る。`login`, `logout` は避ける
    get 'sign_in'
    post 'sign_out'
  end

  # RP として振る舞う
  namespace :connect do
    # とりあえず Google を使う. TODO: `accounts.nslabs.jp` に切り替えること
    resource :google_oauth2, only:[:create, :show], controller:'google_oauth2'
  end


  # グローバルマスタ########################################################
  
  # 消費税マスタ
  resources :vats

  # 為替レート
  # ●●
  
  
  resources :books do
    # 管理 ########################################################
    
    member do
      # 締め処理
      get :period_end_close
    end

    # 会計期間
    resources :period_ends

    
    # 財務会計 ########################################################
    
    # 会計部門マスタ
    resources :divisions do
      member do
        post :enable_div
      end
    end
    
    # 勘定科目マスタ
    resources :account_titles do
      member do
        post :enable_ac
      end
    end

    # 仕訳帳・振替伝票
    resources :journals do
      # `:id` 伝票番号 + date= 伝票日付
      member do 
        post 'add_line'
      end
      collection do # `:id` なし
        get 'list'
        #post 'remove_line' クライアント側で実装
      end
    end
    
    # 予定取引
    # ●●

    # 総勘定元帳.
    # `:id` は不要. コントローラは `GeneralLedgersController`
    resource :general_ledger do
      collection do
        get 'list'
      end
    end

    # 簡易な固定資産
    # ●●

    # 予算 -- バージョン管理があるから複数形
    resources :budgets do
    end

    # 科目別税区分別消費税集計表
    # ●●

    # 財務諸表テンプレート
    resources :report_templates do
    end

    # 財務諸表テンプレートの各科目
    resources :reporting_titles do
      collection do
        #post 'new_line'
      end

      member do
        post 'edit_cxl'
      end
    end

    # 財務諸表・予算実績対比
    resource :statements do
      collection do
        get 'list'
        # 月次推移
        get 'month'
      end
    end

    
    # 販売管理 ########################################################

    # 販売請求書
    # ●●

    
    # 購買管理 ########################################################

    # (購買) 請求書
    resources :invoices

    # 経費精算
    resources :expenses

    
    # 取引先 ########################################################

    # 取引先マスタ
    resources :partners do
      collection do
        get "search"
      end
    end

    
    # 入出金 ########################################################

    # 取引照合: Credit Card Reconciliation
    resources :cc_reconciliations

    # 銀行振込み
    resources :payments

    # 出納帳
    # `:id` は不要
    resource :cashbook

    # 資金口座マスタ
    resources :cash_accounts
  
    # 金融投資
    # ●●

    # 借入金
    # ●●

  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/account_titles_controller.rb
# Q's Web Accounting Book
# Copyright (c) 2002-2007,2010-2011,2013,2024 Hisashi HORIKAWA. All rights reserved.
#   https://www.nslabs.jp/ac/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# 勘定科目マスタ
class AccountTitlesController < ApplicationController
  # `@book` の設定を兼ねる
  before_action :check_if_user_can_access_book

  before_action :set_account_title, only: %i[ show edit update destroy enable_ac]

  # GET /account_titles or /account_titles.json
  # `params[:tab]` root 科目
  def index
    # System 科目は未利用でも表示.
    roots = AccountTitle.tree_roots(@book)
    @tab = (roots.find do |x| x.id == params[:tab].to_i end) || roots.first
    @ac_sections = roots.map do |root|
      {name: root.name, link: root.id, active: root.id == @tab.id}
    end

    r = { id: @tab.id, name: @tab.name, aggregate: @tab.aggregate,
          show_link: "/books/#{@book.id}/account_titles/#{@tab.id}",
          sort: @tab.sort, active: true, "_children": [] }
    r["_children"] = @tab.children_json(@book, @tab)
    @ac_tab_ary = [r]
  end


  # 勘定科目の詳細
  # GET /account_titles/1 or /account_titles/1.json
  def show
  end


  # 新しい勘定科目 (画面)
  # GET /account_titles/new
  def new
    @admin_user = current_user  # ●● TODO: fix!
    @system_item = @admin_user ? true : false
    
    @account_title = AccountTitle.new
    @parent_id = nil
    @active = true
  end


  # POST /account_titles or /account_titles.json
  def create
    @admin_user = current_user  # ●● TODO: fix!
    @system_item = @admin_user ? params[:system_item] : false
    
    @account_title = AccountTitle.new(account_title_params.permit(
                        %i[aggregate sort name name_short description sign kind ac_type enable_invoice payable_id tax_group]) )
    @active = params[:active] || false
    
    if !params[:parent_id].blank?
      parent = AccountTitle #.left_outer_joins(:ac_activations)
                   .where('(book_id IS NULL or book_id = ?) AND aggregate IS TRUE AND account_titles.id = ?', @book.id, params[:parent_id])
                   .take
    end

    @account_title.book_id = @book.id if !@system_item
    #@account_title.suppl_code = 0
    
    # 実在科目を root に置くのは不可
    if !@account_title.aggregate && !parent
      @account_title.errors.add :base, "実在科目は root に置けません。"
      render :new, status: :unprocessable_entity
      return
    end
    
    begin
      ActiveRecord::Base.transaction do
        @account_title.save!
        if parent
          parent.add_child(@account_title,
                           main_parent:true, weight:1)
        end

        if !@system_item
          AcOvrd.create! account_title_id: @account_title.id,
                         book_id: @book.id, active:@active,
                         name: @account_title.name,
                         name_short: @account_title.name_short,
                         sign: @account_title.sign
        end
      end
    rescue ActiveRecord::RecordInvalid
      @parent_id = parent.id if parent
      render :new, status: :unprocessable_entity
      return
    end
    
    redirect_to( {action:'show', id: @account_title.id},
                 notice: "Account title was successfully created." )
  end

  
  # GET /account_titles/1/edit
  def edit
    @admin_user = current_user  # ●● TODO: fix!
    @system_item = @admin_user && !@account_title.book_id ? true : false

    ovrd = @account_title.ac_ovrd(@book)
    if ovrd
      # `ovrd.attributes` だと unknown attribute 'account_title_id' for AccountTitle
      # -> 手書きする
      @account_title.assign_attributes(
        name: ovrd.name, name_short:ovrd.name_short, sign:ovrd.sign )
      @active = ovrd.active
    end
  end


  # PATCH/PUT /account_titles/1 or /account_titles/1.json
  def update
    @admin_user = current_user  # ●● TODO: fix!
    @system_item = @admin_user ? params[:system_item] : false

    @active = params[:active] || false  # `|| false` を付けないと nil になる

    # ここでは保存しない
    # `aggregate` 後から変更不可.
    @account_title.assign_attributes(account_title_params.permit(
                                       %i[sort name name_short description sign kind ac_type enable_invoice payable_id tax_group]) )
    
    if @system_item
      ovrd = @account_title.ac_ovrd(@book)
    else
      # いつでも ovrd をつくる
      ovrd = @account_title.ac_ovrd(@book) || AcOvrd.new(
               account_title_id: @account_title.id, book_id: @book.id)
      ovrd.assign_attributes(
               active: @active, name: @account_title.name,
               name_short:@account_title.name_short, sign: @account_title.sign )
    end

    ActiveRecord::Base.transaction do
      if @system_item || @account_title.book_id
        @account_title.save!
      end
      if !@system_item
        ovrd.save!
      else
        ovrd.delete if ovrd
      end
    rescue ActiveRecord::RecordInvalid
      @parent_id = @account_title.main_parent ? @account_title.main_parent.id : nil
      render :edit, status: :unprocessable_entity 
      return
    end
        
    redirect_to( {action:'show', id:@account_title},
                 notice: "Account title was successfully updated." )
  end

  
  # 勘定科目を利用する: book ごと
  # POST
  def enable_ac
    ovrd = AcOvrd.find_or_initialize_by(
             book_id: @book.id, account_title_id: @account_title.id) do |m|
      m.active     = true
      m.name       = @account_title.name
      m.name_short = @account_title.name_short
      m.sign       = @account_title.sign
    end
    ovrd.save!

    index() # ary を更新
    # turbo stream で返す
    render( turbo_stream: turbo_stream.replace("ac_table_frame", partial:'ac_table_frame'))
  end


  # DELETE /account_titles/1 or /account_titles/1.json
  def destroy
    if !@account_title.book_id # system_item
      flash[:alert] = "システム科目は削除できません"
      render :show, status: :unprocessable_entity
      return
    end
    
    ActiveRecord::Base.transaction do
      # `where()` して消すのは `delete_all()`
      AcOvrd.where('book_id = ? AND account_title_id = ?', @book.id, @account_title.id).delete_all
        
        # 途中の場合, 間を詰めないといけない (`distance` を減らす)
        # @note 生 SQL の書き方が `execute()` ばかり引っ掛かるが、安全でない
        #       正しいメソッドは `find_by_sql()`.
        #       `SELECT` 文を書きたい場合は `select()`, `from()`
      AccountTitleTree.find_by_sql [<<EOS, @account_title.id, @account_title.id, @account_title.id, @account_title.id]
UPDATE account_title_trees
    SET distance = distance - 1
    WHERE
        parent_id IN (SELECT parent_id FROM account_title_trees
                                       WHERE child_id = ? AND parent_id <> ?)
        AND child_id IN (SELECT child_id FROM account_title_trees
                                         WHERE parent_id = ? AND child_id <> ?)
EOS
        
      # あとは削除するだけ
      AccountTitleTree.where('parent_id = ? OR child_id = ?',
                               @account_title.id, @account_title.id).delete_all
      @account_title.destroy!
    end
      
    redirect_to( {controller:"account_titles", action:"index", book_id:@book.id},
                 notice: "Account title was successfully destroyed." )
  end


private #############################################
  
  # Use callbacks to share common setup or constraints between actions.
  def set_account_title
    @account_title = AccountTitle.where('(book_id IS NULL or book_id = ?) AND id = ?', @book.id, params[:id]).take
    raise ActiveRecord::RecordNotFound if !@account_title
  end

  # Only allow a list of trusted parameters through.
  def account_title_params
    params.require(:account_title)
  end

end # class AccountTitlesController 

app/views/account_titles/_ac_table_frame.html.erb
<div id="ac_table_frame" data-controller="account-titles">

  <script type="application/json" id="tbl-json-data">
    <%= @ac_tab_ary.to_json.html_safe %>
  </script>
 

  <div id="ac-tbl" >
  </div>

</div>

app/views/account_titles/_form.html.erb
  <%= error_messages_for form.object %>

<% if @admin_user  %>
  <div class="row mb-3 text-bg-info">
    <label class="col-sm-2 col-form-label">System item:</label>
    <div class="col-sm-10">
      <label class="form-check-label">
        <%= check_box_tag :system_item, '1', @system_item,
                               class:"form-check-input" %>
        System item の作成・編集
      </label> 
    </div>
  </div>
<% end %>
  
  <div class="row mb-3">
    <label class="col-sm-2 col-form-label" for="parent_id">親:</label>
    <div class="col-sm-10">
<% if ['new', 'create'].include?(controller.action_name) %>  
      <%= select_tag 'parent_id',
                options_from_collection_for_select(AccountTitle.aggregations(@book),
                                                   :id, :name, @parent_id),
              include_blank:"(Root)", class:"form-select" %>
<% else %>
      <%= @account_title.main_parent ? @account_title.main_parent.name : "(root)" %>
<% end %>
    </div>
  </div>


  <div class="row mb-3">
    <label  class="col-sm-2 col-form-label">集計科目?:</label>
    <div class="col-sm-10">
<% if controller.action_name != "new" && controller.action_name != 'create' %>
      <%= @account_title.aggregate ? "集計科目" : "実在科目" %>
<% else %>
      <label class="form-check-label">
        <%= form.radio_button :aggregate, true, class:"form-check-input" %>
        集計科目 (仕訳を発生させない)
      </label>
      <label class="form-check-label">
        <%= form.radio_button :aggregate, false, class:"form-check-input" %>
        実在科目
      </label>
      <div class="form-text">
        <em style="color:red">※後から変更できません。</em>
      </div>
<% end %>      
    </div>
  </div>

  <div class="row mb-3">
    <label class="col-sm-2 col-form-label">Active:</label>
    <div class="col-sm-10">
      <label class="form-check-label">
        <%= check_box_tag :active, '1', @active, class:"form-check-input" %>
        Active
      </label> 
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :sort, "表示順:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :sort, class:"form-control" %>
      <div class="form-text">英字始まり, 英数のみ</div>
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :name, "名前:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :name, class:"form-control" %> 
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :name_short, "短縮名:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :name_short, class:"form-control" %> 
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :description, "説明:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_area :description, rows:5, class:"form-control" %> 
    </div>
  </div>


<% if ['new', 'create'].include?(controller.action_name) ||
      !@account_title.aggregate %>

<h2>実在科目のみ</h2>

  <div class="row mb-3">
    <%= form.label :sign, "残高か発生か:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
<% if ['new', 'create'].include?(controller.action_name) %>  
      <label class="form-check-label">
        <%= form.radio_button :ac_type, 1, class:"form-check-input" %> 残高</label>
      <label class="form-check-label">
        <%= form.radio_button :ac_type, 4, class:"form-check-input" %> 発生額</label>
      <div class="form-text">
        <em style="color:red">※後から変更できません。</em>
      </div>
<% else %>
      <%= @account_title.ac_type == 1 ? "残高科目" :
             (@account_title.ac_type == 4 ? "発生科目" : raise) %>
<% end %>
    </div>
  </div>


  <div class="row mb-3">
    <%= form.label :sign, "元帳の表示正残:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <label class="form-check-label">
        <%= form.radio_button :sign, +1, class:"form-check-input" %>
        借方</label>
      <label class="form-check-label">
        <%= form.radio_button :sign, -1, class:"form-check-input" %>
        貸方</label>
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :kind, "業務アプリ:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
<% AccountTitle::KINDS.to_a.each do |x| %>
      <div class="form-check">
        <label class="form-check-label">
          <%= form.radio_button :kind, x[0], class:"form-check-input" %>
          <%= x[1] %>
        </label>
      </div>
<% end %>
      <div class="form-check">
        <label class="form-check-label">
          <%= form.radio_button :kind, 0, class:"form-check-input" %>
          なし
        </label>
      </div>
    </div>
  </div>

  
  <div class="row mb-3">
    <%= form.label :kind, "購買請求書・経費精算:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <table class="table table-sm">
        <tr><th>利用可?  <th>債務科目
        <tr>
          <td>
            <label class="form-check-label">
              <%= form.check_box :enable_invoice, class:"form-check-input" %>
              Yes
            </label>
          <td>
            <%= form.collection_select :payable_id, AccountTitle.ap_items(@book),
                                    :id, :name %>
      </table>
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :tax_group, "税グループ:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :tax_group,
                      (Vat::TAX_GROUP.to_a.map do |v| [v[1], v[0]] end),
                      {include_blank:"消費税不可"} %>
    </div>
  </div>

<% end %>
  

app/views/account_titles/edit.html.erb
<% @page_title = "勘定科目の編集" %>

<%= form_with(model: @account_title,
              url:{controller:'account_titles', action:'update', id: @account_title.id}) do |form| %>
  <%= render "form", form:form %>

  <div>
    <%= link_to "Cancel", 
                {controller:'account_titles', action:'show', id: @account_title.id},
              class:"btn btn-secondary", role:"button" %>

    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/account_titles/index.html.erb
<% @crumbs = []
   @page_title = "勘定科目の一覧" %>

●● TODO: ここに検索ボックスがほしい

<div class="row">
  <div class="col">
    <nav class="nav flex-column nav-pills">
<% @ac_sections.each do |ac_section| %>
<%   if ac_section[:active] %>
      <a class="nav-link active" aria-current="page"><%= ac_section[:name] %></a>
<%   else %>
      <%= link_to ac_section[:name], "/books/#{@book.id}/account_titles/?tab=#{ac_section[:link]}", class: "nav-link" %>
<%   end %>
<% end %>
    </nav>
  </div>
  
  <div class="col">
    
<% # separate parts to enable the table refresh.
  %>
<%= render partial: "ac_table_frame" %>

  </div>
</div>


<hr />
<p><%= link_to "新しい勘定科目...", action: 'new' %>

app/views/account_titles/new.html.erb
<% @page_title = "新しい勘定科目" %>

<%= form_with(model: @account_title,
              url:{controller:'account_titles', action:'create'}) do |form| %>
  <%= render "form", form:form %>

  <div>
    <%= link_to "Cancel", "./",
                class:"btn btn-secondary", role:"button" %>

    <%= form.submit class:"btn btn-primary"  %>
  </div>
<% end %>

app/views/account_titles/show.html.erb
<% @crumbs = [
     {name: "勘定科目の一覧", link: "./" } # 末尾の "/" 必須
   ]
   @page_title = "勘定科目: " + @account_title.name %>


<% ovrd = @account_title.ac_ovrd(@book) %>

<table class="table">
  <tr><th>Sort: <td><%= @account_title.sort %>
  <tr><th>System科目?: <td><%= @account_title.book_id ? "No" : "Yes" %> 
  <tr><th>親:
    <td>
<% if @account_title.parents.size > 0 
     @account_title.parents.each do |parent| %>
      <%= parent.sort %>
      <%= parent.name %>
<%   end %>
<% else %>
      親はありません
<% end %>

  <tr><th>集計科目?:
    <td><%= @account_title.aggregate ? "集計科目" : "実在科目" %>  

  <tr><th>Active?:
    <td><%= ovrd ? ovrd.active : "-" %>
        
  <tr><th>Name:
    <td>
<% if ovrd %>
      <%= ovrd.name %><br /><span class="text-secondary"><%= @account_title.name %></span>
<% else %>
      <%= @account_title.name %>      
<% end %>

  <tr><th>Name short:
    <td>
<% if ovrd %>
      <%= ovrd.name_short %><br /><span class="text-secondary"><%= @account_title.name_short %></span>
<% else %>
      <%= @account_title.name_short %>      
<% end %>

  <tr><th>元帳の表示正残:
    <td>
      <%= ovrd ? ovrd.sign : @account_title.sign %>          
</table>


<div>
  <%= link_to "Edit this account title...", edit_book_account_title_path(@book, @account_title) %> |

  <%= button_to "Destroy this account title",
                {controller:'account_titles', action:'destroy', id:@account_title.id},
                method: :delete, data:{turbo_confirm:'OK?'} %>
</div>