config/routes.rb
# Q's Web Accounting Book
# Copyright (c) 2002-2007,2010-2011,2013,2024 Hisashi HORIKAWA. All rights reserved.
#   https://www.nslabs.jp/ac/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# ルーティング
Rails.application.routes.draw do

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest


  # You can have the root of your site routed with "root"
  root :to => 'welcome#index'

  # 単数形は `controller:` でクラスを指定.
  resource :account, controller:'account' do
    # Sorcery と名前が被る。`login`, `logout` は避ける
    get 'sign_in'
    post 'sign_out'
  end

  # RP として振る舞う
  namespace :connect do
    # とりあえず Google を使う. TODO: `accounts.nslabs.jp` に切り替えること
    resource :google_oauth2, only:[:create, :show], controller:'google_oauth2'
  end


  # グローバルマスタ########################################################
  
  # 消費税マスタ
  resources :vats

  # 為替レート
  # ●●
  
  
  resources :books do
    # 管理 ########################################################
    
    member do
      # 締め処理
      get :period_end_close
    end

    # 会計期間
    resources :period_ends

    
    # 財務会計 ########################################################
    
    # 会計部門マスタ
    resources :divisions do
      member do
        post :enable_div
      end
    end
    
    # 勘定科目マスタ
    resources :account_titles do
      member do
        post :enable_ac
      end
    end

    # 仕訳帳・振替伝票
    resources :journals do
      # `:id` 伝票番号 + date= 伝票日付
      member do 
        post 'add_line'
      end
      collection do # `:id` なし
        get 'list'
        #post 'remove_line' クライアント側で実装
      end
    end
    
    # 予定取引
    # ●●

    # 総勘定元帳.
    # `:id` は不要. コントローラは `GeneralLedgersController`
    resource :general_ledger do
      collection do
        get 'list'
      end
    end

    # 簡易な固定資産
    # ●●

    # 予算 -- バージョン管理があるから複数形
    resources :budgets do
    end

    # 科目別税区分別消費税集計表
    # ●●

    # 財務諸表テンプレート
    resources :report_templates do
    end

    # 財務諸表テンプレートの各科目
    resources :reporting_titles do
      collection do
        #post 'new_line'
      end

      member do
        post 'edit_cxl'
      end
    end

    # 財務諸表・予算実績対比
    resource :statements do
      collection do
        get 'list'
        # 月次推移
        get 'month'
      end
    end

    
    # 販売管理 ########################################################

    # 販売請求書
    # ●●

    
    # 購買管理 ########################################################

    # (購買) 請求書
    resources :invoices

    # 経費精算
    resources :expenses

    
    # 取引先 ########################################################

    # 取引先マスタ
    resources :partners do
      collection do
        get "search"
      end
    end

    
    # 入出金 ########################################################

    # 取引照合: Credit Card Reconciliation
    resources :cc_reconciliations

    # 銀行振込み
    resources :payments

    # 出納帳
    # `:id` は不要
    resource :cashbook

    # 資金口座マスタ
    resources :cash_accounts
  
    # 金融投資
    # ●●

    # 借入金
    # ●●

  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/vat.rb
# Q's Web Accounting Book
# Copyright (c) 2002-2007,2010-2011,2013,2024 Hisashi HORIKAWA. All rights reserved.
#   https://www.nslabs.jp/ac/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# 消費税マスタ
class Vat < ApplicationRecord

  # 'JP'
  validates_presence_of :country

  validates_presence_of :tax_code
  validates_uniqueness_of :tax_code

  validates_presence_of :name

  validates_presence_of :effective_day

  validates_presence_of :tax_rate

  validates_presence_of :tax_group

  # 非課税仕入は不課税(対象外) と区別しない。対称性なさすぎ.
  TAX_GROUP = {
    10 => "課税売上(標準)",
    20 => "課税売上(軽減)",
    50 => "非課税売上",
    60 => "輸出免税",
    210 => "課税仕入(標準)",
    220 => "課税仕入(軽減)",
    250 => "非課税仕入",  # 勘定科目側だけ、利用。
    270 => "ﾘﾊﾞｰｽﾁｬｰｼﾞ" }

  
  ##########################################################################
  # Class Methods
  
  # グルーピングなしで返す
  def self.active_items(book, date)
    Vat.where('effective_day <= ?', date)
       .order(:tax_group).order(effective_day: :desc)
  end

end


# 固定資産の売却

=begin
   CASH          100  /  固定資産の売却収入 100 (9)

   固定資産の売却原価 700 / 固定資産の取得価額 1,000
   減価償却累計額     300

   => 固定資産売却損 = 91 - 700 = 609

=end

app/controllers/vats_controller.rb
# Q's Web Accounting Book
# Copyright (c) 2002-2007,2010-2011,2013,2024 Hisashi HORIKAWA. All rights reserved.
#   https://www.nslabs.jp/ac/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


# 消費税マスタ
class VatsController < ApplicationController
  before_action :set_vat, only: %i[ show edit update destroy ]

  # GET /vats or /vats.json
  def index
    @vats = Vat.all
  end

  # GET /vats/1 or /vats/1.json
  def show
  end

  # GET /vats/new
  def new
    @vat = Vat.new
  end

  # GET /vats/1/edit
  def edit
  end

  # POST /vats or /vats.json
  def create
    @vat = Vat.new(vat_params)

    respond_to do |format|
      if @vat.save
        format.html { redirect_to vat_url(@vat), notice: "Vat was successfully created." }
        format.json { render :show, status: :created, location: @vat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vats/1 or /vats/1.json
  def update
    respond_to do |format|
      if @vat.update(vat_params)
        format.html { redirect_to vat_url(@vat), notice: "Vat was successfully updated." }
        format.json { render :show, status: :ok, location: @vat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vats/1 or /vats/1.json
  def destroy
    @vat.destroy!

    respond_to do |format|
      format.html { redirect_to vats_url, notice: "Vat was successfully destroyed." }
      format.json { head :no_content }
    end
  end


private
  # Use callbacks to share common setup or constraints between actions.
  def set_vat
    @vat = Vat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def vat_params
    params.require(:vat).permit(:tax_group)
  end
end

app/views/vats/_form.html.erb
<%= form_with(model: vat) do |form| %>
  <% if vat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vat.errors.count, "error") %> prohibited this vat from being saved:</h2>

      <ul>
        <% vat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-3">
    <%= form.label :tax_group, "税グループ:", class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.select :tax_group,
                      (Vat::TAX_GROUP.to_a.map do |v| [v[1], v[0]] end) %>
    </div>
  </div>
  
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vats/_vat.html.erb
<% # 一覧に表示
  %>

<div id="<%= dom_id vat %>" class="row">
  <div class="col-1">
    <%= vat.country %>
  </div>
  <div class="col-1">
    <%= vat.tax_code %>
  </div>
  <div class="col-2">
    <%= vat.name %>
  </div>

  <div class="col-2">
    <%= Vat::TAX_GROUP[vat.tax_group] ? Vat::TAX_GROUP[vat.tax_group] : "● #{vat.tax_group}" %>
  </div>
  
  <div class="col-2">
    <%= vat.effective_day %>
  </div>
  <div class="col-1">
    <%= vat.tax_rate %>
  </div>

  <div class="col-1">
    <%= link_to "詳細", vat %>
  </div>
</div>

app/views/vats/edit.html.erb
<% @page_title = "消費税の編集" %>

<%= render "form", vat: @vat %>


<div>
  <%= link_to "Show this vat", @vat %> |
  <%= link_to "Back to vats", vats_path %>
</div>

app/views/vats/index.html.erb
<% @crumbs = [
     {name: "会計帳簿の一覧", link: "/books/"} ]
   @page_title = "消費税マスタ" %>

<div class="row thead">
  <div class="col-1">国</div>
  <div class="col-1">税コード</div>
  <div class="col-2">名前</div>
  <div class="col-2">税グループ</div>
  <div class="col-2">開始日</div>
  <div class="col-1">税率</div>
</div>

<div id="vats">
<% @vats.each do |vat| %>
  <%= render vat %>
<% end %>
</div>

<hr />
<p><%= link_to "New vat...", new_vat_path %>  ●● TODO: 編集は admin に制限

app/views/vats/new.html.erb
<% @page_title = "新しい消費税マスタ" %>

<%= render "form", vat: @vat %>


<div>
  <%= link_to "Back to vats", vats_path %>
</div>

app/views/vats/show.html.erb
<% @page_title = @vat.name %>

<%= render @vat %>

<div>
  <%= link_to "Edit this vat", edit_vat_path(@vat) %> |
  <%= link_to "Back to vats", vats_path %>

  <%= button_to "Destroy this vat", @vat, method: :delete %>
</div>